export const WMO_DESCRIPTIONS = {
	"0": "Sunny",
	"1": "Partly Cloudy",
	"2": "Partly Cloudy",
	"3": "Cloudy",
	"4": "Smoky",
	"5": "Hazy",
	"6": "Dusty Air",
	"7": "Blowing Dust",
	"8": "Dust Whirls",
	"9": "Duststorm",
	"10": "Mist",
	"11": "Foggy",
	"12": "Foggy",
	"13": "Lightning",
	"14": "Visible Precipitation",
	"15": "Distant Rain",
	"16": "Nearby Rain",
	"17": "Thunderstorm",
	"18": "Windy",
	"19": "Funnel Cloud",
	"20": "Drizzle/Snow Grains",
	"21": "Light Rain",
	"22": "Light Snow",
	"23": "Snowing",
	"24": "Freezing Drizzle",
	"25": "Rain Showers",
	"26": "Snow Showers",
	"27": "Hail Showers",
	"28": "Foggy",
	"29": "Thunderstorm",
	"30": "Light Duststorm",
	"31": "Duststorm",
	"32": "Duststorm",
	"33": "Severe Duststorm",
	"34": "Severe Duststorm",
	"35": "Severe Duststorm",
	"36": "Blowing Snow",
	"37": "Heavy Snow",
	"38": "Blowing Snow",
	"39": "Heavy Snowfall",
	"40": "Foggy",
	"41": "Patchy Fog",
	"42": "Foggy",
	"43": "Foggy",
	"44": "Foggy",
	"45": "Foggy",
	"46": "Foggy",
	"47": "Foggy",
	"48": "Rime Foggy",
	"49": "Rime Foggy",
	"50": "Light Drizzle",
	"51": "Light Drizzle",
	"52": "Moderate Drizzle",
	"53": "Moderate Drizzle",
	"54": "Heavy Drizzle",
	"55": "Heavy Drizzle",
	"56": "Freezing Drizzle",
	"57": "Freezing Drizzle",
	"58": "Drizzle & Rain",
	"59": "Heavy Rain",
	"60": "Light Rain",
	"61": "Steady Light Rain",
	"62": "Sudden Rain",
	"63": "Steady Rain",
	"64": "Heavy Intermittent Rain",
	"65": "Heavy Continuous Rain",
	"66": "Slight Rain",
	"67": "Heavy Rain",
	"68": "Slight Rain-Snow",
	"69": "Moderate Rain-Snow",
	"70": "Slight Snowflakes",
	"71": "Slight Snowfall",
	"72": "Moderate Snowfall",
	"73": "Snow Storm",
	"74": "Flurry",
	"75": "Snowfall",
	"76": "Diamond Dust",
	"77": "Tiny Snowfall",
	"78": "Snowflakes",
	"79": "Ice Pellets",
	"80": "Slight Rain",
	"81": "Heavy Rain",
	"82": "Heavy Rainfall",
	"83": "Slight Rain & Snow",
	"84": "Heavy Rain & Snow",
	"85": "Slight Snow",
	"86": "Heavy Snowr",
	"87": "Hail",
	"88": "Heavy Hail",
	"89": "Slight Hail Shower",
	"90": "Heavy Hail Shower",
	"91": "Slight Rain",
	"92": "Heavy Rain",
	"93": "Slight Snow",
	"94": "Heavy Rain",
	"95": "Thunderstorm",
	"96": "Thunderstorm",
	"97": "Heavy Thunderstorm",
	"98": "Mixed Storm",
	"99": "Thunderstorm",
} as const;
